return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = false,
	main = "nvim-treesitter.config",
	opts = {
		ensure_installed = {
			"c",
			"lua",
			"vim",
			"html",
			"css",
			"javascript",
			"typescript",
			"tsx",
			"json",
			"jsonc",
			"yaml",
			"python",
			"go",
			"gomod",
			"gowork",
			"gosum",
			"svelte",
			"markdown",
			"java",
			"kotlin",
			"latex",
			"hcl",
			"terraform",
			"rust",
			"toml",
		},
		sync_install = false,
		auto_install = true,
		highlight = { enable = true, disable = { "html" } },
		indent = { enable = true },
	},
}
